### ISSUE TITLE
(REQ) ON/OFF Toggle

### ISSUE THREAD

**Issue by gmorks** [regiellis/ComfyUI-EasyPony#1]
works like a charm, more than an issue an idea to add a toggle to mute/bypass it when is in workflows that change to a non-pony model

**Comment by regiellis** [comment]
I have decided to close this as "will not fix";
My reasoning is due to the recent updates I have made in 1.2.0. I am now allowing model loading directly on 
the node. Which means:
- Now it does make sense to really use it in other workflows...since it is not just generating a prompt
- Favor the Comfyui mute node function (ctrl+B), this allows the node to not be processed and take up resources, whereas
if I was to add a disabled...the node would still process upstream.
